In [98]:
tab= np.array([[1,0,3],[2,3,2],[3,1,1]])  
d = [] 
for i in range(len(tab)): 
    d+= [tab[i][i]] 
print(d)
#lp(d)
        

[1, 3, 1]


In [99]:
import numpy as np
#tab= np.array([[1,0,0],[1,1,1],[0,1,1]]) 
x= -1*tab[0]+tab[1] 
# newa= np.array(tab[0],x,tab[2]) 
#print(x)  
-tab[1][0]
#print(tab)  
#len(tab)
print(tab[0][0] )
print(tab[1][0] )
print(tab[2][0]) 
tab[:,0] # how to index columns in python 

1
2
3


array([1, 2, 3])

In [100]:
def mtrace(matrix): 
    d = [] 
    for i in range(len(matrix)): 
            d+= [matrix[i][i]] # collects components of diagonal in a vector 
    #print(d)
    lp(d) # sums the components of the diagonal

In [101]:
#alist=[1,2,3,5,2,5] 
#def lp(a):
a=[1,2,3,3,2]
for i in range(len(a)): 
    if i+1 > len(a)-1: 
        break 
    else: 
        prod= a[i]*a[i+1] #sums to components of a list
        a[i+1]=prod # replaces the next component of list with previous product 
         
print(prod) 

36


In [102]:
def lp(a):   #list product
    for i in range(len(a)): 
        if i+1 > len(a)-1: 
            break 
        else: 
            prod= a[i]*a[i+1]
            a[i+1]=prod 
             #return prod
    print(prod) 

In [103]:

happy= np.array([[1.,2,5],[1,2,3],[0,0,0]]) 
#x= -1*tab[0]+tab[1] we are going to try to build this for square matrices
# newa= np.array(tab[0],x,tab[2]) 
# print(x)  
#tab[1]=x 
#print(tab) 
for i in range(len(happy)):
    if i is not 0 and happy[i][i]  is not 0: # conditions for loop for pivot 
           happy[i]= -happy[i][0]*happy[0]+happy[i]  #does row operations to create pivot 


print(happy) 
            
        



[[ 1.  2.  5.]
 [ 0.  0. -2.]
 [ 0.  0.  0.]]


In [104]:
#falls apart rn for casses with bad zero placement, specifically zero in pivot 
# need to always keep track of types being passed in only need one float in matrix for it  
# to work 

happy= np.array([[1.,2,5,4],[3,2,4,3],[3,7,5,7],[2,3,1,9,8],[4,3,2,1]]) 
for j in range(happy.shape[1]): # shape gets propper j goes over cols
    for i in range(happy.shape[0]):  # i goes over rows
        if i is not j :    # screens out the pivot positions
                if happy[j][j] == 0: 
                    if happy[j][j] == 0 and j == len(happy)-1:# termination of last 0 pivot
                        break 
                    for k in range(len(happy[:,j])):  
                        if happy[:,j][k] is  0: 
                            break 
                        
                        elif happy[:,j][k] is not 0 and k > j: 
                            happy[[j,k]] = happy[[k,j]] # swaps two rows acts as row operations
                           # print(happy) 

                happy[j] = happy[j]/happy[j][j] # creates the pivots for each col
                
                happy[i]= -happy[i][j]*happy[j] + happy[i] # performs the row operations
                print(happy)
                
           

IndexError: tuple index out of range

In [105]:
#this sort of works pretty well compute rref form a square matrix
def rref(m): 
    for j in range(m.shape[1]):
        for i in range(m.shape[0]): 
            if i is not j :    
                    if m[j][j] == 0: 
                        if m[j][j] == 0 and j == len(m)-1: # termination of last 0 pivot
                            break 
                        for k in range(len(m[:,j])):  
                            if m[:,j][k] is  0: 
                                continue 
                        
                            elif m[:,j][k] is not 0 and k > j: 
                                m[[j,k]] = m[[k,j]] # swaps two rows acts as row operations
                            
                                print(m) 
                    m[j] = m[j]/m[j][j] 
                
                    m[i]= -m[i][j]*m[j] + m[i]
                    print(m)
                
        print(m)

In [135]:
# this version can handle most zeros cases
# final issue rn is getting to make sure all pivots exist in case where columns exceed rows

happy= np.array([[0.,0,0],[0,0,0],[0,0,0]]) 

m,n=happy.shape
print(happy)
if n>m : #takes care of an error case with indices 
    n=m 

for j in range(n): # shape gets propper j goes over cols
    for i in range(m):  # i goes over rows
        if j is not i :    # screens out the pivot positions
                if happy[j][j] == 0 : 
                    if happy[j][j] == 0 and j == len(happy)-1:# termination of last 0 pivot
                        if happy[j][j+1] is not 0: 
                            happy[j] = happy[j]/happy[j][j+1]
                            happy[i+1]= -happy[i+1][j+1]*happy[j] + happy[i+1]
                            happy[i]= -happy[i][j+1]*happy[j] + happy[i]
                            print(happy)
                    break 
                    for k in range(len(happy[:,j])):  
                        if happy[:,j][k] is  0: 
                            break 
                        
                        elif happy[:,j][k] is not 0 and k > j: 
                            happy[[j,k]] = happy[[k,j]] # swaps two rows acts as row operations
                           # print(happy) 

                happy[j] = happy[j]/happy[j][j] # creates the pivots for each col
                
                happy[i]= -happy[i][j]*happy[j] + happy[i] # performs the row operations
                print(happy)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


IndexError: index 3 is out of bounds for axis 0 with size 3

In [119]:
happy.shape

(5,)

In [107]:
#generates an identity matrix 
def Id(a,b): 
    I=np.zeros((a,b))
    for j in range(I.shape[1]): 
        I[j][j]=1  
    return I
    
                

In [108]:
#canonical form generator  
def Can(a): 
    canonical= np.hstack((a,Id(a.shape[0],a.shape[0])))   
    return canonical 

In [109]:
r=[]
z=np.array([[1.,2,5],[3,2,4],[3,7,5]]) 
b=np.array([[1.],[2],[3],[0]])
o=[-1.,-2,-5,0,0,0] 

for e in range(3): 
    r.append(tabl[:,6][e]/tabl[:,2][e])
    print(r) 

[0.2]
[0.2, 0.5]
[0.2, 0.5, 0.6]


In [110]:
g=np.array([[1],[2],[4]])
a=[2.,3,4] 
b=[2.,4,7] 
r=[]
4==a[1]
for i in range(3): 
    r.append(a[i]/b[i]) 
print(r)

[1.0, 0.75, 0.5714285714285714]


In [111]:
tabl 
tabl[:m-2,tabl[m-2].index(k)]

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [112]:
def lin(a,b): #gives index of particular entry in list
    for i in range(len(a)): 
        if a[i] == b: 
            return i

In [113]:
# we will use to check if our last row in the tableau is optimal 
# we can see that if our solution is optimial the product our or nonbasic variables 
#will be positive. 
def zs(a): #screens out zeros in product of list 
    for j in range(len(a)): 
        if abs(a[j]-0.)<0.00001 : 
            a[j]=1
    print(a)
    for i in range(len(a)): 
        if i+1 > len(a)-1: 
            break 
        else: 
            prod= a[i]*a[i+1]
            a[i+1]=prod  
    return prod

In [197]:
#simplex algorithm calculator 
# we need to probably use while loop to check if the last entries
# in objective row are positive   
z=np.array([[1.,2,5,4],[3,2,4,3],[3,7,5,7],[2,3,1,9]]) 
b=np.array([[1.],[2],[3],[7]])
o=[-3.,-4,-1,0,0,0,0,0,0] 
tabl=np.vstack((np.hstack((Can(z),b)),o)) # this is our tableau
m,n=tabl.shape
print(tabl) 
while min(tabl[m-1]) < 0: # takes a product of non-basic variables to see if its positive 
    # assigns most negative number to variable  
    v= min(tabl[m-1])
    #print(v) 
    lm=lin(tabl[m-1],v) # gives index of minium entry in objective row 
   # print(lm)
    r=[]
    for e in range(m-1): 
        r.append(tabl[:m-1,n-1][e]/tabl[:m-1,lm][e]) #computes theta ratios
        p = min(r)
        if r[e] is p: 
            a=e  
    piv(tabl,a,lm)   
print('The optimal solution is ',tabl[:m-1,n-1]) 
print('The objective functions value is ',tabl[:,n-1][m-1])

[[ 1.  2.  5.  4.  1.  0.  0.  0.  1.]
 [ 3.  2.  4.  3.  0.  1.  0.  0.  2.]
 [ 3.  7.  5.  7.  0.  0.  1.  0.  3.]
 [ 2.  3.  1.  9.  0.  0.  0.  1.  7.]
 [-3. -4. -1.  0.  0.  0.  0.  0.  0.]]
[[ 0.14285714  0.          3.57142857  2.          1.          0.
  -0.28571429  0.          0.14285714]
 [ 3.          2.          4.          3.          0.          1.
   0.          0.          2.        ]
 [ 0.42857143  1.          0.71428571  1.          0.          0.
   0.14285714  0.          0.42857143]
 [ 2.          3.          1.          9.          0.          0.
   0.          1.          7.        ]
 [-3.         -4.         -1.          0.          0.          0.
   0.          0.          0.        ]]
[[ 0.14285714  0.          3.57142857  2.          1.          0.
  -0.28571429  0.          0.14285714]
 [ 2.14285714  0.          2.57142857  1.          0.          1.
  -0.28571429  0.          1.14285714]
 [ 0.42857143  1.          0.71428571  1.          0.          0.
  

In [174]:
print(z) 
print(Can(z))
print(b) 
L=
print(L)
J=np.vstack((L,o))
print(o) 
print(J)

SyntaxError: invalid syntax (<ipython-input-174-419481bad1ae>, line 4)

In [115]:
km=np.array([[1.,2.,3],[7,6,7],[4,6,8]]) 
km[1] = km[1]/km[1][2] 
m,n=km.shape
for i in range(m): 
    if i is not 1:
        km[i]= -km[i][2]*km[1] + km[i] 
        print(km)

[[-2.         -0.57142857  0.        ]
 [ 1.          0.85714286  1.        ]
 [ 4.          6.          8.        ]]
[[-2.         -0.57142857  0.        ]
 [ 1.          0.85714286  1.        ]
 [-4.         -0.85714286  0.        ]]


In [116]:
def piv(km,a,b): 
    km[a] = km[a]/km[a][b] 
    m,n=km.shape
    for i in range(m): 
        if i is not a:
            km[i]= -km[i][b]*km[a] + km[i] 
            print(km)
